### ISSUE TITLE
Changing color and thickness of the cursor

### ISSUE THREAD

**Issue by hakan-akgul** [srares13/keyboard-cursors-and-selections#3]
Thanks for great extension ✨ 
That is what I am searching for years.

If there will be a setting about changing color and thickness of the cursor, it would be great.

**Comment by srares13** [comment]
Thanks for your appreciation!

### About being able to change the color of inactive selections:
The good news is that, this feature will be implemented. However, what would be a little unpleasantly is that it would have to wait a little longer, because right now I'm working on some more complex functionality features.

<br>

### Thickness of the cursor:
Could you please provide me here with some details, specifically:
- the font you are using
- the size of the font
- if you changed the height of editor's lines or characters
- if you changed the width of the characters
- an image of code/text that also has the inactive cursors about which you would want their thickness to be different

I ask you all these because you may found out a scenario where the thickness of the cursors does not adjust accordingly, and I have to be sure about what's the situation.

**Comment by hakan-akgul** [comment]
Thanks for the good news ✨ 

- font: Ubuntu Mono Ligaturized, JetBrains Mono
- font-size: 15
- line-height: default
- cursor-width: 3
- image: 

<img width="845" alt="image" src="https://github.com/srares13/keyboard-cursors-and-selections/assets/64319895/c1198113-09fa-4f75-bad2-165691f3b64c">

**Comment by hakan-akgul** [comment]
I developed the theme, maybe you want to try 🚀  : [theme-armada](https://marketplace.visualstudio.com/items?itemName=hakan-akgul.armada)

**Comment by srares13** [comment]
Thanks for bringing it to my attention. So the inactive cursors were designed from the beginning to, of course, not be that thin, as seen in the gifs from the readme. It seems that version 1.82 of VS Code changed something that affected that, but now it's fixed, I launched the newer version of the extension 1.1.3, which fixes this.

I've also learned that you can change the width of the normal cursor from VS Code options. Some time soon I'll make that if the user set a specific width for the normal cursor, then the inactive cursors will be of the same width.

**Comment by hakan-akgul** [comment]
Great!!!

**Comment by srares13** [comment]
Hi again! I think that now with the latest update I covered what was requested with this issue, but I wanna hear your thoughts. Thanks!

This describes the added functionality:

-  You can change the colors of the inactive cursors and selections:

   1. Open the Command Palette (Windows/Linux: `Ctrl+Shift+P`, Mac: `Cmd+Shift+P`).

   2. Search for and select `Preferences: Open Settingts (UI)`.

   3. Once the settings view is open type "kcs", and options like `Kcs: Cursor Color` and `Kcs: Selection Color` will appear. Their value has to be given in hex code.

   <br>

   -  For developers who want to change these colors through their theme, this is an example of how you could do it:
      ```javascript
      const configuration = vscode.workspace.getConfiguration('kcs')
      await configuration.update('cursorColor', '#ff0000', vscode.ConfigurationTarget.Global)
      await configuration.update('selectionColor', '#ff000099', vscode.ConfigurationTarget.Global)
      ```
      Note that you can use transparency, especially for the selection color.

**Comment by hakan-akgul** [comment]
Hello  

That's awesome 🙌🏻   

On the other hand, when a user tries to use the updated version for the first time, the plugin shows the changelog. This is a very nice feature, I think.  

Thanks for all of your efforts.

**Comment by srares13** [comment]
I havent close the issue until now because of what I also said:
> Some time soon I'll make that if the user set a specific width for the normal cursor, then the inactive cursors will be of the same width.

The original requests were the ability to change the color of the inactive cursors, which was implemented, and the original request about the cursor thickness was that it was too thin once a certain version of VS Code was installed - something which was not intended, but solved long ago.

Im not planning to implement yet what I was saying in the quote block, and because the original requests the OP had were met I think, Im gonna close soon this issue. However, if the missing ability described in the block quote becomes a big issue, I will address it.

**Comment by hakan-akgul** [comment]
It is ok for me. I am happy with the current version of the extension. Thank you.

**Comment by srares13** [comment]
All right, good to hear that!
