### ISSUE TITLE
An idea about adding cursor

### ISSUE THREAD

**Issue by hakan-akgul** [srares13/keyboard-cursors-and-selections#4]
I have an idea about adding cursors. Maybe you can consider.

When we press to keybinding, we enter to `add cursor mode`
While we press to `space` we can continue to adding cursor.
After we press to `enter` the cursors are activated.

On the other hand when we are in  `add cursor mode` the shape of the cursor may change, so we can aware of it.

It is just an idea that you can consider.

Thanks for the great extension 🚀

**Comment by srares13** [comment]
I really tried to understand the method you are describing, but I couldn't fully understand it :D. I could only guess it, but it will be better if you could elaborate and rephrase every aspect of it, both this one: 
> When we press to keybinding, we enter to add cursor mode
While we press to space we can continue to adding cursor.
After we press to enter the cursors are activated.

and this one:
> On the other hand when we are in add cursor mode the shape of the cursor may change, so we can aware of it.

**Comment by hakan-akgul** [comment]
Actually, there is an extension that already use this logic.  

This link may help: https://github.com/soulshined/Navigator/blob/master/images/sticky-cursors.gif  

You can say go and use this extension 😀, but I wanted to give you an idea. I know it will change the core logic.  

I think that maybe you can like this logic, and maybe you want to implement.

**Comment by srares13** [comment]
As i understand it:
- Press a keybinding to enter into an "add cursor mode"
- While in this mode, press space to add a cursor
- Still while in this mode, press enter to activate the cursors and exit "add cursor mode"

Did i get it right?

**Comment by hakan-akgul** [comment]
Yes, completely right

**Comment by srares13** [comment]
The reason why in that specific situation, an "adding cursor mode" was necessary, is because it used "Space" and "Enter" which are very common keys and already have their functions in the UI/editor control, so it needed a special mode which alters the functions of those keys.

In KCS, to make the cursors and selections being added that way means to change the core behavior, as you also pointed out. But there is no reason for it, because you could map the commands to the desired key combinations, which are still fast to hit (examples: PageUp, PageDown; F1, F2; Alt+X, Alt+Z), and dont require a special mode in which you are adding inactive cursors. Once added you can rely on the fact that you can interact with the UI and editor controls as usual.

**Comment by hakan-akgul** [comment]
I know, I know 😊 

I only wanted to give an idea maybe you want to like and implement.

I am already using the KCS in my daily development environment.

I am closing the issue, so thank you again...
