### ISSUE TITLE
[Feature Request] Use the cursors without need of activating selection

### ISSUE THREAD

**Issue by Giulidan** [srares13/keyboard-cursors-and-selections#5]
Thank you for the extension! 
Could you implement an option to start editing in the cursors without the need of doing the activation command?

I mean, just after placing the cursors, use those cursors when you start typing.

**Comment by srares13** [comment]
I suppose I though of this behavior when I designed the mechanism of the extension, but to truly answer this you gotta help me understand something.

So lets say you want to place two arbitrary cursors. After you placed the first one and you are hitting the arrow keys to choose the position of the second one, how would you place the second without at the same time moving the first? because naturally, you'd want the first one to stay in place while you are choosing the position of the second.

With the current mechanism, if you wish to place two or multiple arbitrary cursors in the document, first you choose their positions, and while choosing successive positions, the previous ones stay in place because those cursors are inactive. If the previous cursors were already active once placed, then they would have moved while you were choosing the positions of the next cursors.

Im waiting for your response.

**Comment by Giulidan** [comment]
Thank you for your response!

I'm new to programming and I don't know about the VSCode extensions limitations, but, why would the first cursor move if you just press the arrow keys? I expect it not to change the cursors unless I type a letter (or in other words, modify the document).

So you can place the first cursor, move the view or the _normal cursor_ to another place, set the second cursor and so on... and the cursors would be active in the moment you start typing.

I think this feature should be optional.

By the way, I found the warning of Uncaught Errors many times, why this could be?

![image](https://github.com/srares13/keyboard-cursors-and-selections/assets/107063361/fa9734a7-0bb2-4c8c-902d-bf80fab831be)

**Comment by srares13** [comment]
So about the errors, I think I solved them. It was something more technical, it did not affect the functionality, but it was bloating the console with errors, so it had to be dealt with. Nonetheless, if there are issues still, inform me.

On the other hand, about the feature request: that sounds very interesting. However there are other actions different from typing that you may do with a cursor, for example shift + arrow combo to select. In this case if the user wants to select something only with the main cursor, then the user will simply hit that combo, alternatively if it is wanted something to be selected from the positions of each inactive cursor, then the user will know that the inactive cursors have to be activated first.

There is more to this. Im working on a feature which allows the inactive cursors react to document edits, so their positions will move across the document accordingly. This feature will be highly tied to the ability of being able to activate the inactive selections on demand.

**Comment by srares13** [comment]
I hope the reasons are understood why this request wont make its way into the extension, at least for now. Im gonna close this one as not planned, but if you still have something to add to this or other matters, you can certainly open another issue!
