### ISSUE TITLE
[Feature Request] An all-in-one command to achieve the major functionalities

### ISSUE THREAD

**Issue by aafulei** [srares13/keyboard-cursors-and-selections#7]
Hi @srares13, first, thanks for the nice extension!

I was looking for a Visual Studio Code equivalent of the [MarkAndMove](https://packagecontrol.io/packages/MarkAndMove) plugin for Sublime Text, and yours seems to be the closest.

To be clear, I use only one command `mark_and_move_do_it_all` in the [MarkAndMove](https://packagecontrol.io/packages/MarkAndMove) plugin, to which I assign <kbd>Ctrl</kbd> + <kbd>J</kbd> as the shortcut.

The convenience is, all the functionalities can be achieved with an all-in-one shortcut <kbd>Ctrl</kbd> + <kbd>J</kbd>. That is,

1. start with a selection and press <kbd>Ctrl</kbd> + <kbd>J</kbd> - place inactive selection no. 1
2. move on and establish a new selection and press <kbd>Ctrl</kbd> + <kbd>J</kbd> - place inactive selection no. 2
3. without moving, press <kbd>Ctrl</kbd> + <kbd>J</kbd> again - activate all the selections (no.1 + no.2)
4. without moving, press <kbd>Ctrl</kbd> + <kbd>J</kbd> again - go back to the status after step 2, as if step 3 never happened

That is, we use an all-in-one command `A` to check if the current selection is identical with the last inactive selection placed -
- if no, then we place a new inactive selection
- if yes, then we check if all the selections are activated -
  - if no, then we activate all the selections
  - if yes, then we restore all the selections to inactive status

---

Another minor question/suggestion is that is it possible that the `KCS: Undo/Redo` be integrated with the general `Undo/Redo`? That is, if the last command is `KCS: Place Inactive Selection`, pressing <kbd>Ctrl</kbd> + <kbd>U</kbd> undos the last place action.

---

Thank you very much!

**Comment by srares13** [comment]
> Hi @srares13, first, thanks for the nice extension!

Your welcome!

---

About your suggestion with an all-in-one command to achieve the major functionalities, the way I understand it, there is a key aspect to this matter: when you are with an active cursor or selection over an inactive one, and hit the all-in-one command, you suggest that the inactive cursors and selections should be activated.

However, the extension already has an existing functionality in this scenario: when you are with an active cursor or selection over an inactive one, and hit the `KCS: Place Inactive Selection` command, that respective inactive cursor or selection will be removed. The idea is that this functionality, in my opinion, shouldnt be lost. If you have multiple inactive cursors and selections, you should be able to selectively remove a certain one if you choose so. - this could be because of various reasons: probably you placed it by mistake, or you dont need it anymore, or you want to relocate it, etc.

So with these being said, I dont see a way for the ability to selectively remove inactive cursors and selections and to also activate them, to be on the same command.

---

About the other suggestion, having the general Undo/Redo integrating the KCS: Undo/Redo, I think that it wouldnt be advisable because:
- Generally, for the Undo/Redo functionality, the editors (including VS Code) register the actions that modify the characters in the document (text characters, tabs, spaces, new lines, etc.) and nothing more. As you can see, if you place some active selections, hit escape or click anywhere to remove them, then hit Undo, VS Code itself wont put back those selections, and this is the case with any other "metadata" on the document.
- It isnt advisable to alter a built-in functionality of the editor, especially when other features of the editor and also other extensions rely on that functionality.
- You could indeed create custom commands which integrate the general Undo/Redo and the one from KCS, but then you would have to let at the user's choice whether or not to replace the built-in Undo/Redo with the custom one. Just by how that sounds, I dont think its worth it, developing and maintaining such a command, in this situation.

---

If you have any other questions, uncertainties, please ask!

**Comment by srares13** [comment]
Or of course, if you have solutions, or if i badly interpreted what you suggested, please tell. However, for how i understood it, the one above is my explanation.

**Comment by aafulei** [comment]
Hi @srares13 thank you for your prompt reply!

Let's focus on the all-in-one command discussion.

From your reply I gladly feel that you understand my idea.

Let me elaborate on it from a user-experience point of view.

To me, all a user want to do for 99% of time is, without touching the mouse, specify a bunch of selections and collect them all together as multi-selected.

So the workflow is

```
# Workflow 1
Add 1
Add 2
Add 3
Add 4
Collect them all
```

Now this is already possible with your current extension, but not possible with only 1 command, i.e. 1 keyboard shortcut.

If your extension could do this with 1 command, then it would gain a lot of popularity, because people go to extensions for simplicity, not for complexity.

I understand your idea. You explained that your current design makes the workflow below also possible

```
# Workflow 2
Add 1
Add 2
Add 3
Remove 2
Add 4
Collect them all
```

I am not arguing against this design and I am happy with everything you've done.

But it would be better if you could add 1 more all-in-one command that deals ***only*** with the first workflow (which I believe would be 99% of the use cases).

The pros & cons would be -
- What if people want to remove 1 selection in the middle like in the second workflow? Then please start it over.
- But, if you don't make mistakes, everything can be simply done with just 1 command, to add and collect selections.

As a user that heavily relies on the keyboard (like many others) I have assigned like 178 keyboard shortcuts, and such an all-in-one command really matters.

Again, it's your extension and your baby, so you have the final say. And, if you are open to pull requests, I might implement it later in future. Thank you!

**Comment by srares13** [comment]
You already mentioned some pros and cons for the all-in-one command, but Im gonna relist them here and also Im gonna develop on them:

### Pros:
1. The first workflow could indeed represent the majority of the situations, hence having just one command would improve the operability.

### Cons:
These mainly represent what you can do with the current workflow, and wouldnt be able to if this is changed into all-in-one command.
1. You have to be with the active cursor over an inactive one to be able to activate them, whereas with the current workflow you can activate them from anywhere you would move, for whatever reason, the active cursor.
2. Selectively removing inactive cursors and selections wouldnt be possible anymore with the same command that places them. To start over would really represent an inconvenience.
3. There are all sorts of use cases, some of them which can demand different workflows. For example [here](https://github.com/microsoft/vscode/issues/20742) was mentioned this one:
> 1- After activating some cursors, edit what you need, how can I disable only one cursor by navigating the file with (up, down, left, right) without affecting the position of the other cursors?
2 - After activating some cursors, edit what you need, how can I activate another cursor by navigating the file with (up, down, left, right) without affecting the position of the other cursors?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So due to the current capabilities and workflow of the extension, the above functionality is also possible.

---

Even if the other use cases that are made possible by the current workflow are not that common (however for some users they might be), the inability to perform the desired action could represent a deal breaker for the users that need it, which I think outweighs the slight improvement in efficiency in the use case you target.

Considering the fact that with an all-in-one command workflow you are still needed to hit something (button/hotkey) in order to activate the inactive cursors and selections, it is not that big of an inconvenience to have a separate command for activating them, especially since you can map them very close, like:
- `CTRL + Key1` (for placement) - `CTRL + Shift + Key1` (for activation)
- `PageDown` - `PageUp`
- `F1` - `F2`
- etc.

To continue on the previous idea, for the use case you target, I had an even more efficient suggestion that was mentioned to me, and that is for the inactive cursors and selections to be activated right when you start editing (so no press of an additional button/hotkey at all). But this also cancels some other capabilities of the extension which i detailed them in that [issue](https://github.com/srares13/keyboard-cursors-and-selections/issues/5) in the second to last comment.

#### The bottom line
I tried to target every important use case and scenario I could think that may occur and which can all be worked out through a single combined workflow that carries the least inconvenience. And I feel like the current workflow does that at the expense of, in certain use cases, having the slight inconvenience of just needing to hit a separate button/hotkey for activation.

---

When we think about that fact that the workflow you suggested can be implemented (by me, or by others through pull requests) as an alternative behavior of the extension, then I would have to let every alternative workflow make its way into the extension, and I've seen quite a number of them. This will have a huge impact over the maintainability of the extension, not being feasible at all. As a conclusion to this, it can be said again the idea I expressed at "The bottom line".

I hope that my reasons do weigh something, and thank you for the understanding!
Nevertheless, feedback is always welcomed!

**Comment by aafulei** [comment]
Thank you for your detailed explanation @srares13 and it's great to have the discussion with you!
